apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260622-145113-uunyjtfm5onv-service
spec:
  selector:
    app: enterprise-system-20260622-145113-uunyjtfm5onv
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
